defmodule Tymeslot.Repo.Migrations.AddEndsNextDayToAvailabilityWindowsTest do
  @moduledoc """
  Covers the migration that lets a weekly window or a date override end on
  the next day. No existing row can violate the new constraints (the column
  is new and defaults to false), so the tests pin the default, what the
  constraints refuse and accept, and what rolling back does to an overnight
  window.
  """

  use Tymeslot.DataCase, async: false

  @moduletag :database
  @moduletag :availability
  @moduletag :migrations

  alias Tymeslot.Repo
  alias Tymeslot.Test.MigrationRunner

  # Generated by `mix ecto.gen.migration add_ends_next_day_to_availability_windows`.
  @version 20_261_005_093_645

  setup do
    schedule = insert(:availability_schedule)
    %{schedule: schedule}
  end

  test "existing windows and overrides arrive as same-day", %{schedule: schedule} do
    MigrationRunner.down!(@version)

    Repo.query!(
      "INSERT INTO weekly_availability (schedule_id, day_of_week, is_available, start_time, end_time, inserted_at, updated_at) VALUES ($1, 1, true, '09:00', '17:00', now(), now())",
      [schedule.id]
    )

    Repo.query!(
      "INSERT INTO availability_overrides (schedule_id, date, override_type, start_time, end_time, inserted_at, updated_at) VALUES ($1, '2027-06-14', 'custom_hours', '10:00', '14:00', now(), now())",
      [schedule.id]
    )

    MigrationRunner.up!(@version)

    assert %{rows: [[false]]} =
             Repo.query!("SELECT ends_next_day FROM weekly_availability WHERE schedule_id = $1", [
               schedule.id
             ])

    assert %{rows: [[false]]} =
             Repo.query!(
               "SELECT ends_next_day FROM availability_overrides WHERE schedule_id = $1",
               [schedule.id]
             )
  end

  test "refuses a next-day window whose end is after its start", %{schedule: schedule} do
    MigrationRunner.rerun!(@version)

    assert_raise Postgrex.Error, ~r/weekly_availability_next_day_end_check/, fn ->
      insert_weekly(schedule.id, ~T[09:00:00], ~T[10:00:00], true)
    end
  end

  test "refuses a next-day window without hours", %{schedule: schedule} do
    MigrationRunner.rerun!(@version)

    assert_raise Postgrex.Error, ~r/weekly_availability_next_day_end_check/, fn ->
      Repo.query!(
        "INSERT INTO weekly_availability (schedule_id, day_of_week, is_available, ends_next_day, inserted_at, updated_at) VALUES ($1, 2, false, true, now(), now())",
        [schedule.id]
      )
    end
  end

  test "accepts an overnight window and a full 24 hours", %{schedule: schedule} do
    MigrationRunner.rerun!(@version)

    insert_weekly(schedule.id, ~T[22:00:00], ~T[02:00:00], true, 1)
    insert_weekly(schedule.id, ~T[00:00:00], ~T[00:00:00], true, 2)

    assert %{num_rows: 2} =
             Repo.query!(
               "SELECT 1 FROM weekly_availability WHERE schedule_id = $1 AND ends_next_day",
               [schedule.id]
             )
  end

  test "refuses a next-day override whose end is after its start", %{schedule: schedule} do
    MigrationRunner.rerun!(@version)

    assert_raise Postgrex.Error, ~r/availability_overrides_next_day_end_check/, fn ->
      Repo.query!(
        "INSERT INTO availability_overrides (schedule_id, date, override_type, start_time, end_time, ends_next_day, inserted_at, updated_at) VALUES ($1, '2027-06-14', 'custom_hours', '09:00', '10:00', true, now(), now())",
        [schedule.id]
      )
    end
  end

  test "rolling back keeps an overnight window's same-day part", %{schedule: schedule} do
    insert_weekly(schedule.id, ~T[22:00:00], ~T[02:00:00], true, 1)

    MigrationRunner.down!(@version)

    assert %{rows: [[~T[22:00:00], ~T[23:59:00]]]} =
             Repo.query!(
               "SELECT start_time, end_time FROM weekly_availability WHERE schedule_id = $1",
               [schedule.id]
             )
  end

  test "rolling back cuts an overnight override to 23:59 and leaves same-day ones", %{
    schedule: schedule
  } do
    insert_override(schedule.id, ~D[2027-06-14], ~T[22:00:00], ~T[03:00:00], true)
    insert_override(schedule.id, ~D[2027-06-15], ~T[10:00:00], ~T[14:00:00], false)

    MigrationRunner.down!(@version)

    assert %{
             rows: [
               [~D[2027-06-14], ~T[22:00:00], ~T[23:59:00]],
               [~D[2027-06-15], ~T[10:00:00], ~T[14:00:00]]
             ]
           } =
             Repo.query!(
               "SELECT date, start_time, end_time FROM availability_overrides WHERE schedule_id = $1 ORDER BY date",
               [schedule.id]
             )
  end

  test "rolling back cuts breaks that cross midnight and leaves the others as stored", %{
    schedule: schedule
  } do
    night = insert_weekly(schedule.id, ~T[22:00:00], ~T[02:00:00], true, 1)
    day = insert_weekly(schedule.id, ~T[09:00:00], ~T[17:00:00], false, 2)

    before_midnight = insert_break(night, ~T[22:30:00], ~T[23:00:00])
    across_midnight = insert_break(night, ~T[23:30:00], ~T[00:30:00])
    after_midnight = insert_break(night, ~T[01:00:00], ~T[01:30:00])
    same_day = insert_break(day, ~T[12:00:00], ~T[13:00:00])

    MigrationRunner.down!(@version)

    assert break_times(before_midnight) == {~T[22:30:00], ~T[23:00:00]}
    assert break_times(across_midnight) == {~T[23:30:00], ~T[23:59:00]}
    assert break_times(after_midnight) == {~T[01:00:00], ~T[01:30:00]}
    assert break_times(same_day) == {~T[12:00:00], ~T[13:00:00]}
  end

  defp insert_override(schedule_id, date, start_time, end_time, ends_next_day) do
    Repo.query!(
      "INSERT INTO availability_overrides (schedule_id, date, override_type, start_time, end_time, ends_next_day, inserted_at, updated_at) VALUES ($1, $2, 'custom_hours', $3, $4, $5, now(), now())",
      [schedule_id, date, start_time, end_time, ends_next_day]
    )
  end

  defp insert_break(weekly_availability_id, start_time, end_time) do
    %{rows: [[id]]} =
      Repo.query!(
        "INSERT INTO availability_breaks (weekly_availability_id, start_time, end_time, inserted_at, updated_at) VALUES ($1, $2, $3, now(), now()) RETURNING id",
        [weekly_availability_id, start_time, end_time]
      )

    id
  end

  defp break_times(id) do
    %{rows: [[start_time, end_time]]} =
      Repo.query!("SELECT start_time, end_time FROM availability_breaks WHERE id = $1", [id])

    {start_time, end_time}
  end

  defp insert_weekly(schedule_id, start_time, end_time, ends_next_day, day \\ 3) do
    %{rows: [[id]]} =
      Repo.query!(
        "INSERT INTO weekly_availability (schedule_id, day_of_week, is_available, start_time, end_time, ends_next_day, inserted_at, updated_at) VALUES ($1, $2, true, $3, $4, $5, now(), now()) RETURNING id",
        [schedule_id, day, start_time, end_time, ends_next_day]
      )

    id
  end
end
