defmodule Tymeslot.Repo.Migrations.RewriteAvailabilityWindowsEndingAtMidnightTest do
  @moduledoc """
  Covers the migration that turns windows ending at 23:59 into windows ending
  at midnight ("00:00 (+1)"). Each test rolls the migration back, writes the
  rows as an older database holds them, and runs `up/0` over them; see
  `Tymeslot.Test.MigrationRunner`.
  """

  use Tymeslot.DataCase, async: false

  @moduletag :database
  @moduletag :availability
  @moduletag :migrations

  alias Tymeslot.Repo
  alias Tymeslot.Test.MigrationRunner

  # Generated by `mix ecto.gen.migration rewrite_availability_windows_ending_at_midnight`.
  @version 20_261_005_143_445

  setup do
    %{schedule: insert(:availability_schedule)}
  end

  test "a window ending at 23:59 or 23:59:59 ends at midnight the next day", %{schedule: schedule} do
    MigrationRunner.down!(@version)
    weekly!(schedule.id, 1, ~T[09:00:00], ~T[23:59:00])
    weekly!(schedule.id, 2, ~T[00:00:00], ~T[23:59:59])

    MigrationRunner.up!(@version)

    assert window(schedule.id, 1) == {~T[09:00:00], ~T[00:00:00], true}
    assert window(schedule.id, 2) == {~T[00:00:00], ~T[00:00:00], true}
  end

  test "other windows, days without hours and backwards rows are left alone", %{
    schedule: schedule
  } do
    MigrationRunner.down!(@version)
    weekly!(schedule.id, 1, ~T[09:00:00], ~T[23:45:00])
    weekly!(schedule.id, 2, nil, nil)
    weekly!(schedule.id, 3, ~T[23:59:30], ~T[23:59:00])

    MigrationRunner.up!(@version)

    assert window(schedule.id, 1) == {~T[09:00:00], ~T[23:45:00], false}
    assert window(schedule.id, 2) == {nil, nil, false}
    assert window(schedule.id, 3) == {~T[23:59:30], ~T[23:59:00], false}
  end

  test "a break running to 23:59 runs to midnight; others keep their times", %{schedule: schedule} do
    MigrationRunner.down!(@version)
    day_id = weekly!(schedule.id, 1, ~T[09:00:00], ~T[23:59:00])
    other_id = weekly!(schedule.id, 2, ~T[09:00:00], ~T[17:00:00])
    break!(day_id, ~T[22:00:00], ~T[23:59:00])
    break!(day_id, ~T[12:00:00], ~T[13:00:00])
    break!(other_id, ~T[12:00:00], ~T[13:00:00])

    MigrationRunner.up!(@version)

    assert breaks(day_id) == [{~T[12:00:00], ~T[13:00:00]}, {~T[22:00:00], ~T[00:00:00]}]
    assert breaks(other_id) == [{~T[12:00:00], ~T[13:00:00]}]
  end

  test "overrides with hours ending at 23:59 end at midnight; unavailable ones are untouched", %{
    schedule: schedule
  } do
    MigrationRunner.down!(@version)
    override!(schedule.id, ~D[2027-06-14], "custom_hours", ~T[18:00:00], ~T[23:59:00])
    override!(schedule.id, ~D[2027-06-15], "available", ~T[10:00:00], ~T[23:59:59])
    override!(schedule.id, ~D[2027-06-16], "unavailable", nil, nil)
    override!(schedule.id, ~D[2027-06-17], "custom_hours", ~T[10:00:00], ~T[14:00:00])

    MigrationRunner.up!(@version)

    assert overrides(schedule.id) == [
             {~D[2027-06-14], ~T[18:00:00], ~T[00:00:00], true},
             {~D[2027-06-15], ~T[10:00:00], ~T[00:00:00], true},
             {~D[2027-06-16], nil, nil, false},
             {~D[2027-06-17], ~T[10:00:00], ~T[14:00:00], false}
           ]
  end

  test "rolling back restores 23:59 on the rewritten rows and their breaks", %{schedule: schedule} do
    MigrationRunner.down!(@version)
    day_id = weekly!(schedule.id, 1, ~T[00:00:00], ~T[23:59:00])
    break!(day_id, ~T[22:00:00], ~T[23:59:00])
    override!(schedule.id, ~D[2027-06-14], "custom_hours", ~T[18:00:00], ~T[23:59:00])
    MigrationRunner.up!(@version)

    MigrationRunner.down!(@version)

    assert window(schedule.id, 1) == {~T[00:00:00], ~T[23:59:00], false}
    assert breaks(day_id) == [{~T[22:00:00], ~T[23:59:00]}]
    assert overrides(schedule.id) == [{~D[2027-06-14], ~T[18:00:00], ~T[23:59:00], false}]
  end

  test "rolling back leaves windows that run past midnight to the earlier migration", %{
    schedule: schedule
  } do
    weekly!(schedule.id, 1, ~T[22:00:00], ~T[02:00:00], true)

    MigrationRunner.down!(@version)

    assert window(schedule.id, 1) == {~T[22:00:00], ~T[02:00:00], true}
  end

  defp weekly!(schedule_id, day, start_time, end_time, ends_next_day \\ false) do
    %{rows: [[id]]} =
      Repo.query!(
        "INSERT INTO weekly_availability (schedule_id, day_of_week, is_available, start_time, end_time, ends_next_day, inserted_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, now(), now()) RETURNING id",
        [schedule_id, day, not is_nil(start_time), start_time, end_time, ends_next_day]
      )

    id
  end

  defp break!(weekly_id, start_time, end_time) do
    Repo.query!(
      "INSERT INTO availability_breaks (weekly_availability_id, start_time, end_time, sort_order, inserted_at, updated_at) VALUES ($1, $2, $3, 0, now(), now())",
      [weekly_id, start_time, end_time]
    )
  end

  defp override!(schedule_id, date, type, start_time, end_time) do
    Repo.query!(
      "INSERT INTO availability_overrides (schedule_id, date, override_type, start_time, end_time, inserted_at, updated_at) VALUES ($1, $2, $3, $4, $5, now(), now())",
      [schedule_id, date, type, start_time, end_time]
    )
  end

  defp window(schedule_id, day) do
    %{rows: [[start_time, end_time, ends_next_day]]} =
      Repo.query!(
        "SELECT start_time, end_time, ends_next_day FROM weekly_availability WHERE schedule_id = $1 AND day_of_week = $2",
        [schedule_id, day]
      )

    {start_time, end_time, ends_next_day}
  end

  defp breaks(weekly_id) do
    %{rows: rows} =
      Repo.query!(
        "SELECT start_time, end_time FROM availability_breaks WHERE weekly_availability_id = $1 ORDER BY start_time",
        [weekly_id]
      )

    Enum.map(rows, &List.to_tuple/1)
  end

  defp overrides(schedule_id) do
    %{rows: rows} =
      Repo.query!(
        "SELECT date, start_time, end_time, ends_next_day FROM availability_overrides WHERE schedule_id = $1 ORDER BY date",
        [schedule_id]
      )

    Enum.map(rows, &List.to_tuple/1)
  end
end
