defmodule Tymeslot.Repo.Migrations.SplitAvailabilityScheduleBuffersTest do
  @moduledoc """
  Covers the migration that replaces `availability_schedules.buffer_minutes`
  with `buffer_before_minutes` and `buffer_after_minutes`.

  The old column carried no range constraint, so each backfill test rolls the
  migration back, writes the old column directly and runs `up/0` over it: the
  only way to show what the copy and the clamp do to rows a real database
  holds. The constraint tests round-trip it too, because the test database is
  already migrated and would otherwise only show whatever constraint it
  happens to carry. See `Tymeslot.Test.MigrationRunner`.

  The old column survives `up/0`, because the previous release still selects
  it; the tests below pin that, including the default a row gets when this
  release inserts it without naming the column.
  """

  use Tymeslot.DataCase, async: false

  @moduletag :database
  @moduletag :availability
  @moduletag :migrations

  alias Tymeslot.Repo
  alias Tymeslot.Test.MigrationRunner

  # Generated by `mix ecto.gen.migration split_availability_schedule_buffers`.
  @version 20_261_002_130_255

  test "copies the old buffer into both new ones" do
    schedule = insert(:availability_schedule)
    MigrationRunner.down!(@version)
    set_old_buffer(schedule.id, 30)

    MigrationRunner.up!(@version)

    assert buffers_of(schedule.id) == {30, 30}
  end

  test "keeps the old buffer column and its value for the previous release" do
    schedule = insert(:availability_schedule)
    MigrationRunner.down!(@version)
    set_old_buffer(schedule.id, 500)

    MigrationRunner.up!(@version)

    assert old_buffer_of(schedule.id) == 500
  end

  test "a schedule inserted without the old buffer gets its default of 15" do
    MigrationRunner.rerun!(@version)
    schedule = insert(:availability_schedule, buffer_before_minutes: 5, buffer_after_minutes: 40)

    assert old_buffer_of(schedule.id) == 15
  end

  test "clamps an old buffer outside 0..120 into range" do
    over = insert(:availability_schedule)
    under = insert(:availability_schedule)
    MigrationRunner.down!(@version)
    set_old_buffer(over.id, 500)
    set_old_buffer(under.id, -10)

    MigrationRunner.up!(@version)

    assert buffers_of(over.id) == {120, 120}
    assert buffers_of(under.id) == {0, 0}
  end

  test "refuses a before-buffer outside 0..120" do
    schedule = insert(:availability_schedule)
    MigrationRunner.rerun!(@version)

    assert_raise Postgrex.Error, ~r/availability_schedules_buffer_before_minutes_range/, fn ->
      Repo.query!("UPDATE availability_schedules SET buffer_before_minutes = 121 WHERE id = $1", [
        schedule.id
      ])
    end
  end

  test "refuses an after-buffer outside 0..120" do
    schedule = insert(:availability_schedule)
    MigrationRunner.rerun!(@version)

    assert_raise Postgrex.Error, ~r/availability_schedules_buffer_after_minutes_range/, fn ->
      Repo.query!("UPDATE availability_schedules SET buffer_after_minutes = -1 WHERE id = $1", [
        schedule.id
      ])
    end
  end

  test "rolling back keeps the larger of the two buffers" do
    schedule = insert(:availability_schedule, buffer_before_minutes: 10, buffer_after_minutes: 40)

    MigrationRunner.down!(@version)

    assert old_buffer_of(schedule.id) == 40
  end

  test "rolling back restores the old buffer where an earlier draft dropped it" do
    schedule = insert(:availability_schedule, buffer_before_minutes: 10, buffer_after_minutes: 40)
    Repo.query!("ALTER TABLE availability_schedules DROP COLUMN buffer_minutes")

    MigrationRunner.down!(@version)

    assert old_buffer_of(schedule.id) == 40
  end

  defp set_old_buffer(id, minutes) do
    Repo.query!("UPDATE availability_schedules SET buffer_minutes = $1 WHERE id = $2", [
      minutes,
      id
    ])
  end

  defp old_buffer_of(id) do
    %{rows: [[buffer]]} =
      Repo.query!("SELECT buffer_minutes FROM availability_schedules WHERE id = $1", [id])

    buffer
  end

  defp buffers_of(id) do
    %{rows: [[buffer_before, buffer_after]]} =
      Repo.query!(
        "SELECT buffer_before_minutes, buffer_after_minutes FROM availability_schedules WHERE id = $1",
        [id]
      )

    {buffer_before, buffer_after}
  end
end
