import Config

# Configure environment
config :tymeslot, environment: :dev

# Configure upload directory for development
config :tymeslot, :upload_directory, Path.expand("uploads")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :tymeslot, TymeslotWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  url: [host: "localhost", port: String.to_integer(System.get_env("PORT") || "4000"), scheme: "http"],
  check_origin: [
    "http://localhost:#{System.get_env("PORT") || "4000"}",
    "http://127.0.0.1:#{System.get_env("PORT") || "4000"}"
  ],
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    System.get_env("SECRET_KEY_BASE") ||
      "1H+dLz1eQCL1mH8vjh5SJUR2Z5QULWP9bH3j8+BwnBSfS9J74akhHrGFpjezqJqd",
  live_view: [signing_salt: System.get_env("LIVE_VIEW_SIGNING_SALT") || "GGsBdYdE5AbmpACB"],
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:tymeslot, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:tymeslot, ~w(--watch)]},
    tailwind_scheduling: {Tailwind, :install_and_run, [:scheduling, ~w(--watch)]},
    tailwind_quill: {Tailwind, :install_and_run, [:quill, ~w(--watch)]},
    tailwind_rhythm: {Tailwind, :install_and_run, [:rhythm, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :tymeslot, TymeslotWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/tymeslot_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :tymeslot, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Configure the database
config :tymeslot, Tymeslot.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "tymeslot_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Configure Oban for development
config :tymeslot, Oban,
  repo: Tymeslot.Repo,
  plugins: [Oban.Plugins.Pruner],
  queues: [
    default: 10,
    emails: 5,
    video_rooms: 3,
    calendar_events: 3,
    calendar_integrations: 2
  ]

# Enable swoosh api client for Postmark adapter
config :swoosh, :api_client, Swoosh.ApiClient.Hackney
