import Config

# Configure environment
config :tymeslot, environment: :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
# Get deployment type and configure check_origin accordingly
deployment_type = System.get_env("DEPLOYMENT_TYPE", "cloudron")

check_origin_config =
  case deployment_type do
    "cloudron" ->
      # Cloudron handles this through its reverse proxy, disable origin checking
      false

    "docker" ->
      # For Docker deployment, require PHX_HOST to be set for origin checking
      case System.get_env("PHX_HOST") do
        # Disable if PHX_HOST not set
        nil -> false
        host -> ["https://#{host}", "http://#{host}"]
      end

    _ ->
      false
  end

config :tymeslot, TymeslotWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: check_origin_config

# Enable secure cookies in production
config :tymeslot, :secure_cookies, true

# SSL is handled by Cloudron's reverse proxy
# force_ssl: [hsts: true]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Tymeslot.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
